In [20]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, normalize

데이터의 단위가 다르면 숫자가 큰 것들에 끌려다닐 수 밖에 없음

어떻게 하면 단위를 맞출 수 있을까?

[스케일링]

1) MinMaxScaler : 0 ~ 1

2) StandardScaler : 평균은 0, 분산은 1 (정규분포 형태)

3) Normalizer : 0 ~ 1 (거리니까)

각각 사용하는 종류가 다름

In [21]:
np.random.seed(100)
data_array = list()

for i in range(1, 100):
    r = np.random.randint(0, i*10, 10)
    data_array.extend(r)

data_array.extend(np.zeros(100))
data_array

[8,
 8,
 3,
 7,
 7,
 0,
 4,
 2,
 5,
 2,
 2,
 14,
 2,
 17,
 16,
 15,
 4,
 11,
 16,
 9,
 29,
 22,
 2,
 27,
 12,
 4,
 1,
 13,
 21,
 19,
 36,
 4,
 27,
 3,
 7,
 1,
 14,
 7,
 16,
 2,
 41,
 30,
 19,
 34,
 27,
 46,
 49,
 30,
 48,
 47,
 39,
 45,
 38,
 44,
 18,
 0,
 56,
 34,
 53,
 10,
 17,
 13,
 30,
 17,
 53,
 68,
 50,
 53,
 0,
 13,
 57,
 76,
 3,
 70,
 3,
 79,
 10,
 60,
 3,
 48,
 52,
 43,
 36,
 5,
 71,
 38,
 86,
 42,
 84,
 76,
 33,
 58,
 42,
 22,
 0,
 55,
 98,
 19,
 53,
 68,
 62,
 50,
 68,
 35,
 23,
 9,
 48,
 21,
 25,
 54,
 6,
 37,
 102,
 116,
 58,
 39,
 107,
 94,
 51,
 30,
 121,
 66,
 17,
 45,
 89,
 35,
 16,
 12,
 86,
 109,
 67,
 20,
 138,
 8,
 93,
 119,
 92,
 44,
 57,
 127,
 0,
 73,
 66,
 144,
 133,
 90,
 34,
 94,
 77,
 129,
 14,
 115,
 33,
 148,
 24,
 28,
 135,
 2,
 63,
 113,
 130,
 145,
 74,
 30,
 67,
 156,
 165,
 82,
 145,
 138,
 141,
 81,
 117,
 25,
 143,
 108,
 122,
 11,
 101,
 38,
 116,
 22,
 55,
 57,
 87,
 179,
 176,
 181,
 145,
 42,
 93,
 172,
 144,
 51,
 182,
 183,
 83,
 100,
 42,
 18

In [22]:
data = pd.DataFrame({"scaling_data": data_array})
print(data)

      scaling_data
0              8.0
1              8.0
2              3.0
3              7.0
4              7.0
...            ...
1085           0.0
1086           0.0
1087           0.0
1088           0.0
1089           0.0

[1090 rows x 1 columns]


In [23]:
# 0부터 977까지의 값이 만들어져 있음

print(f"max : {data.max()}")
print(f"min : {data.min()}")

max : scaling_data    977.0
dtype: float64
min : scaling_data    0.0
dtype: float64


In [24]:
# 선형회귀 때 주로 사용
# MinMaxScaler() : 0과 1을 포함함
scaler = MinMaxScaler()

In [25]:
data_n = scaler.fit_transform(data)
data_n

array([[0.00818833],
       [0.00818833],
       [0.00307062],
       ...,
       [0.        ],
       [0.        ],
       [0.        ]])

In [26]:
print(data_n.min())
print(data_n.max())

0.0
1.0


In [27]:
# 분류할 때 주로 사용
# 정규분포를 따른다는 가정 하에 정규분포 형식으로 바꿈
scaler = StandardScaler()
data_n = scaler.fit_transform(data)
data_n

array([[-0.98416062],
       [-0.98416062],
       [-1.00595372],
       ...,
       [-1.01902959],
       [-1.01902959],
       [-1.01902959]])

In [32]:
# 유클리드 거리 치환 -> 딥러닝
data_n = normalize([data["scaling_data"]], norm="l2")
data_n

array([[0.00073974, 0.00073974, 0.0002774 , ..., 0.        , 0.        ,
        0.        ]])