In [ ]:
a = 1
b = 200
c = 1000

In [ ]:
a

1

In [ ]:
a + b + c

1201

# markdown cell

명령어

enter : edit mode

esc : command mode


**edit mode**

ctlr + enter : 실행

shift + enter : 실행 및 다음 cell

alt + enter : 실행 및 새로운 cell


**command mode**

a : 위에 cell 추가

b : 아래에 cell 추가

y : code cell로 변경

m : markdown cell로 변경

! : shell 명령어 사용 (cmd창)

% : magic function 사용 (!와 비슷하지만 python 명령어이다!)

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.25.0'

In [ ]:
# tab : 자동 완성
# shift tab 설명
np.array

<function numpy.array>

In [ ]:
# numpy.ndarray
# n-dimensional array (n개의 차원을 가진 array로 바꿈)
# 파이썬의 리스트는 컬렉션일 뿐 행렬이 아님
arr01 = np.array([1, 2, 3, 4, 5])
arr01

array([1, 2, 3, 4, 5])

In [ ]:
type(arr01)

numpy.ndarray

In [ ]:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
arr02 = [[1.1, 2.2, 3.3], [4, 5, 6]]
arr02

[[1.1, 2.2, 3.3], [4, 5, 6]]

In [ ]:
# 타입이 다른 리스트를 배열로 바꿀 경우 더 큰 타입으로 바뀜 
# 하나가 실수면 다른 것도 실수로
arr02 = np.array(arr02)
arr02

array([[1.1, 2.2, 3.3],
       [4. , 5. , 6. ]])

In [ ]:
arr02.shape

(2, 3)

In [ ]:
arr03 = [
            [["1"], [2], [3]],
            [[4], [5], [6]],
            [[7], [8], [9]],
            [[10], [11], [12]]
        ]
arr03

[[['1'], [2], [3]], [[4], [5], [6]], [[7], [8], [9]], [[10], [11], [12]]]

In [ ]:
arr03 = np.array(arr03)
arr03

array([[['1'],
        ['2'],
        ['3']],

       [['4'],
        ['5'],
        ['6']],

       [['7'],
        ['8'],
        ['9']],

       [['10'],
        ['11'],
        ['12']]], dtype='<U11')

In [ ]:
# 큰 4개 안에 3개가 들어있고 그 안에 1개가 들어있음
arr03.shape

(4, 3, 1)

In [ ]:
# 한꺼번에 출력하면 마지막만 출력됨
arr01.ndim
arr02.ndim
arr03.ndim

3

In [ ]:
# 각각 출력해주면 값이 셋 다 나옴
print(arr01.ndim)
print(arr02.ndim)
print(arr03.ndim)

1
2
3


In [ ]:
# 코드 실행 결과를 셀에 자동으로 표시하고 싶을 때
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
# 해당 배열에 포함된 모든 요소의 개수를 반환
arr01.size
arr02.size
arr03.size

5

6

12

In [ ]:
# 배열의 차원 수를 나타내는 속성
arr01.ndim
arr02.ndim
arr03.ndim

1

2

3

In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
type(np.arange(3))

numpy.ndarray

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
arr04 = np.arange(0, 11, 2)
arr04
type(arr04)

array([ 0,  2,  4,  6,  8, 10])

numpy.ndarray

In [ ]:
# 행이 하나인 경우에 열 개수만 나옴
arr04.shape

(6,)

In [ ]:
arr04 = arr04.reshape(2, 3)
arr04

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [ ]:
arr04.shape

(2, 3)

In [ ]:
arr05 = np.arange(100)
arr05
arr05.shape
type(arr05)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

(100,)

numpy.ndarray

In [ ]:
# -1 : numpy가 알아서 추론
arr05 = arr05.reshape(2, -1)
arr05
arr05.shape

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

(2, 50)

In [ ]:
# 100개를 3으로 나눌 수 없이 때문에 에러
arr05.reshape(3, -1)

ValueError: cannot reshape array of size 100 into shape (3,newaxis)

In [ ]:
# 첫번째 차원 : 2개의 차원
# 두번째 차원 : -1 (넘파이가 알아서 해줘)
# 세번째 차원 : 크기가 5인 배열 (차원의 길이(length) 또는 크기(size))
arr05 = arr05.reshape(2, -1 ,5)
arr05

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [ ]:
arr05.shape
arr05.ndim

(2, 10, 5)

3

In [ ]:
np.arange(10).reshape(2, -1, 1)

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [ ]:
# 0으로 채워진 행렬 만들기
arr06 = np.zeros(5)

# 1로 채워진 행렬 만들기
arr07 = np.ones(10)

# 비워진 행렬 만들기(무의미한 값들이 채워짐)
arr08 = np.empty(5)

In [ ]:
arr06
arr07
arr08

array([0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.09915305e-311,
       1.27362187e-310])

In [ ]:
# 5개의 서로 균등한 간격을 가지는 숫자를 만듦
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# (2, 3)의 행렬을 만들고
# 그걸 모두 1로 채우겠다(full)
np.full((2, 3),1)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# 단위 행렬 (행렬 곱 항등원)

# 단위 행렬(identity matrix) : 정사각 행렬로
# 주 대각선의 원소가 1이고, 
# 나머지 원소는 모두 0인 행렬

# 항등원 : 곱했을 때 항상 같은 수가 나오는 것

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 0보다 크거나 같고 1보다 작은 숫자 임의로 만들어줌
np.random.random()

np.random.random(5)
np.random.random((2, 3))

0.16570642814746595

array([0.42797302, 0.74575313, 0.3427161 , 0.00403965, 0.35212789])

array([[0.00125417, 0.74233407, 0.68401945],
       [0.8878312 , 0.55844967, 0.40321514]])

In [ ]:
# 넘파이의 난수 생성기의 시드 값을 1로 고정하여 일관된 난수를 생성하도록 함
# 반복해도 일정하게 고정된 값이 나옴
np.random.seed(1)
np.random.randint(0, 10, (2, 3))

array([[8, 8, 6],
       [2, 8, 7]])

In [ ]:
# 표준 정규분포에 따라서 랜덤한 값을 가져옴
np.random.randn(5)
np.random.randn(2, 3)

array([ 0.93155816,  1.70693497, -0.89191376,  1.73559653, -0.63110833])

array([[-0.90734336,  0.37475197, -0.47338275],
       [-0.45452082, -0.08533806,  1.50318838]])

In [ ]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(100, dtype=float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])