In [2]:
import numpy as np

In [3]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print(a + 1)
print(a - 2)
print(a * 3)
print(a / 4)
print(a % 5)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[0.25 0.5  0.75]
 [1.   1.25 1.5 ]
 [1.75 2.   2.25]]
[[1 2 3]
 [4 0 1]
 [2 3 4]]


In [5]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a.sum()

45

In [7]:
# axis
# 0: (행을 기준으로) 열 / 1: (열을 기준으로) 행
print(a.sum(axis=0))
print(a.sum(axis=1))

[12 15 18]
[ 6 15 24]


In [8]:
a.max()

9

In [9]:
print(np.max(a))
print(np.max(a, axis=0))
print(np.max(a, axis=1))

9
[7 8 9]
[3 6 9]


In [10]:
print(a.min())
print(np.min(a))
print(np.min(a, axis=0))
print(np.min(a, axis=1))

1
1
[1 2 3]
[1 4 7]


In [11]:
print(a.mean())
print(np.mean(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

5.0
5.0
[4. 5. 6.]
[2. 5. 8.]


In [12]:
print(median())

NameError: name 'median' is not defined

In [ ]:
print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [ ]:
print(a.std())
print(np.std(a))
print(np.std(a, axis=0))
print(np.std(a, axis=1))

2.581988897471611
2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [ ]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
# e^x : 지수함수
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [ ]:
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [13]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
b = np.arange(3, 30, 3).reshape(3, 3)
c = np.arange(20, 2, -2).reshape(3, 3)

In [15]:
print(b)
print(c)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[20 18 16]
 [14 12 10]
 [ 8  6  4]]


In [16]:
b + c

array([[23, 24, 25],
       [26, 27, 28],
       [29, 30, 31]])

In [17]:
b - c

array([[-17, -12,  -7],
       [ -2,   3,   8],
       [ 13,  18,  23]])

In [18]:
b / c

array([[0.15      , 0.33333333, 0.5625    ],
       [0.85714286, 1.25      , 1.8       ],
       [2.625     , 4.        , 6.75      ]])

In [19]:
print(np.add(b, c))
print(np.subtract(b, c))
print(np.multiply(b, c))
print(np.divide(b, c))
print(np.divmod(b, c)) # 찾아보기

[[23 24 25]
 [26 27 28]
 [29 30 31]]
[[-17 -12  -7]
 [ -2   3   8]
 [ 13  18  23]]
[[ 60 108 144]
 [168 180 180]
 [168 144 108]]
[[0.15       0.33333333 0.5625    ]
 [0.85714286 1.25       1.8       ]
 [2.625      4.         6.75      ]]
(array([[0, 0, 0],
       [0, 1, 1],
       [2, 4, 6]]), array([[ 3,  6,  9],
       [12,  3,  8],
       [ 5,  0,  3]]))


In [20]:
b @ c

array([[216, 180, 144],
       [594, 504, 414],
       [972, 828, 684]])

In [21]:
np.matmul(b, c)

array([[216, 180, 144],
       [594, 504, 414],
       [972, 828, 684]])

In [22]:
np.dot(b, c)

array([[216, 180, 144],
       [594, 504, 414],
       [972, 828, 684]])