In [1]:
import numpy as np

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [3]:
a = np.random.randint(1, 100, (3, 3))
a

array([[20, 38, 57],
       [50, 30, 46],
       [69,  7, 29]])

In [5]:
b = a.copy()
b

array([[20, 38, 57],
       [50, 30, 46],
       [69,  7, 29]])

In [8]:
c = a.copy()
c
b.sort()
b
c.sort(axis=0)
c

array([[20, 38, 57],
       [50, 30, 46],
       [69,  7, 29]])

array([[20, 38, 57],
       [30, 46, 50],
       [ 7, 29, 69]])

array([[20,  7, 29],
       [50, 30, 46],
       [69, 38, 57]])

In [9]:
d = a.copy()
d.sort(axis=1)
d

array([[20, 38, 57],
       [30, 46, 50],
       [ 7, 29, 69]])

In [10]:
e = np.arange(25).reshape((5, 5))
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
e[0]

array([0, 1, 2, 3, 4])

In [12]:
e[0][0]

0

In [13]:
# fancy indexing
e[0, 0] 

0

In [15]:
# 행도 열도 둘 다 1번 인덱스부터 시작
e[1:, 1:]

# 먼저 행을 1번 인덱스부터 한 다음에,
# 다시 또 행을 1번 인덱스부터 함
e[1:][1:] 

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
# 슬라이싱할 때 1번지 인덱스부터 -1(뒤에서 두번째)까지
e[1:-1, 1:-1]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [17]:
e[np.array([0, 1])] # 0번째랑 1번째 출력됨

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
# (0,0) : 0
# (1,1) : 6
# (2,2) : 12

e[(0, 1, 2), (0, 1, 2)]

array([ 0,  6, 12])

In [19]:
e[e%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [20]:
e[e < 15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
e < 15

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])