In [1]:
import numpy as np

In [8]:
#  "ndarray" : "N-dimensional array"
# 1차원 데이터 / 3개의 데이터를 가지고 있음
array1 = np.array([1, 2, 3])
print(f"array1 type : {type(array1)}")
print(f"array1 array 형태 : {array1.shape}")

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (3,)


In [10]:
# 2차원 데이터 / 2개의 로우 / 3개의 컬럼
array2 = np.array([[1, 2, 3], 
                  [4, 5, 6]])
print(f"array2 type : {type(array2)}")
print(f"array2 array 형태 : {array2.shape}")

array2 type : <class 'numpy.ndarray'>
array2 array 형태 : (2, 3)


In [11]:
# 2차원 데이터 / 1개의 로우 / 3개의 컬럼
array3 = np.array([[1, 2, 3,]])
print(f"array3 type : {type(array3)}")
print(f"array3 array 형태 : {array3.shape}")

array3 type : <class 'numpy.ndarray'>
array3 array 형태 : (1, 3)


In [14]:
# 데이터 차원 확인하기
print(f"array1:{array1.ndim}차원, array2: {array2.ndim}차원, array3: {array3.ndim}차원")

array1:1차원, array2: 2차원, array3: 2차원


In [16]:
# 데이터 타입 확인
list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [19]:
# 데이터 타입이 섞여 있다면?
# 데이터 타입이 더 큰 데이터 타입으로 변환됨
list2 = [1, 2, "test"]
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [20]:
# 메모리 절약을 위해서 타입 변경도 가능
array_int = np.array([1, 2, 3])
array_float = array_int.astype("float64")
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [21]:
array_int1 = array_float.astype("int32")
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [23]:
# float형을 int 형으로 변경하면 소수점 이하는 없어짐
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype("int32")
print(array_int2, array_int2.dtype)

[1 2 3] int32


In [24]:
# 테스트용으로 데이터를 만들거나
# 대규모의 데이터를 일괄적으로 초기화해야할 경우

# arange()

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [25]:
# zeros()
# 튜플 형태의 shape 값을 입력하면 
# 모든 값을 0으로 채운 해당 shape 값을 가진 ndarray로 반환

zero_array = np.zeros((3, 2), dtype="int32")
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [26]:
# ones
# 튜플 형태의 shape 값을 입력하면
# 모든 값을 1로 채운 해당 shape 값을 가진 ndarray로 반환
# 타입은 default로 float

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [28]:
array1 = np.arange(10)
print(f"array1 \n {array1}")

array2 = array1.reshape(2, 5)
print(f"array2 \n {array2}")

array3 = array1.reshape(5, 2)
print(f"array3 \n {array3}")

array1 
 [0 1 2 3 4 5 6 7 8 9]
array2 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [30]:
# -1 : 로우랑 컬럼 알아서 계산해서 채워 넣어라
rray1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print(f"array2 shape : {array2.shape}")

array3 = array3.reshape(5, -1)
print(f"array3 shape : {array3.shape}")

[0 1 2 3 4 5 6 7 8 9]
array2 shape : (2, 5)
array3 shape : (5, 2)


In [32]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print(f"array3d : \n {array3d.tolist()}")
print(type(array3d))

array3d : 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
<class 'numpy.ndarray'>


In [34]:
# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print(f"array5 : \n {array5.tolist()}")
print(f"array5 shape: {array5.shape}")

array5 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [35]:
# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print(f"array6 : \n {array6.tolist()}")
print(f"array6 shape: {array6.shape}")

array6 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [40]:
# 인덱싱

array1 = np.arange(start=1, stop=10)
print(f"array1 : {array1}")

value = array1[2]
print(f"value : {value}")

# 타입은 더이상 ndarray가 아니고 그 안에 들어있는 데이터값
print(type(value))

array1 : [1 2 3 4 5 6 7 8 9]
value : 3
<class 'numpy.int32'>


In [41]:
print(f"맨 뒤의 값 : {array1[-1]}, 맨 뒤에서 두 번째 값 : {array1[-2]}")

맨 뒤의 값 : 9, 맨 뒤에서 두 번째 값 : 8


In [42]:
array1[0] = 9
array1[8] = 0
print(f"array1 : {array1}")

array1 : [9 2 3 4 5 6 7 8 0]


In [47]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print(f"(row=0, col=0) index 가리키는 값 : {array2d[0, 0]}")
print(f"(row=0, col=1) index 가리키는 값 : {array2d[0, 1]}")
print(f"(row=1, col=0) index 가리키는 값 : {array2d[1, 0]}")
print(f"(row=2, col=2) index 가리키는 값 : {array2d[2, 2]}")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값 : 1
(row=0, col=1) index 가리키는 값 : 2
(row=1, col=0) index 가리키는 값 : 4
(row=2, col=2) index 가리키는 값 : 9


In [48]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [49]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

[1 2 3]


In [50]:
array5 = array1[3:]
print(array5)

[4 5 6 7 8 9]


In [51]:
array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]


In [55]:

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(f"array2d : \n {array2d}")

print(f"array2d[0:2, 0:2] \n {array2d[0:2, 0:2]}")
print(f"array2d[1:3, 0:3] \n {array2d[1:3, 0:3]}")
print(f"array2d[1:3, :] \n {array2d[1:3, :]}")
print(f"array2d[:, :] \n {array2d[:, :]}")
print(f"array2d[:2, 1:] \n {array2d[:2, 1:]}")
print(f"array2d[:2, 0] \n {array2d[:2, 0]}")


array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [56]:
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [57]:
print(array2d[0])
print(array2d[1])

[1 2 3]
[4 5 6]


In [59]:
print(f"array2d[0] shape : {array2d[0].shape}, array2d shape : {array2d[1].shape}")

array2d[0] shape : (3,), array2d shape : (3,)


In [60]:
# 팬시 인덱싱
# 리스트나 ndarray로 인덱스 집합을 지정하면
# 해당 위치에 해당하는 ndarray를 반환하는 인덱싱 방식

In [65]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

array3 = array2d[[0, 1], 2]
print(f"array2[[0, 1], 2] => {array3.tolist()}")

array4 = array2d[[0, 1], 0:2]
print(f"array2[[0, 1], 0:2] => {array4.tolist()}")

array4 = array2d[[0, 1]]
print(f"array2[[0, 1]] => {array4.tolist()}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[[0, 1], 2] => [3, 6]
array2[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


In [66]:
# 불린 인덱싱

array1d = np.arange(start=1, stop=10)

# [] 안에 array1d > 5 Boolean indexing을 적용

array3 = array1d[array1d > 5]
print(f"array1d > 5 불린 인덱싱 결과값 : {array3}")

array1d > 5 불린 인덱싱 결과값 : [6 7 8 9]


In [67]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [68]:
boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])
array3 = array1d[boolean_indexes]
print(f"불린 인덱스로 필터링 결과: {array3}")

불린 인덱스로 필터링 결과: [6 7 8 9]


In [69]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print(f"일반 인덱스로 필터링 결과 : {array4}")

일반 인덱스로 필터링 결과 : [6 7 8 9]
